import styles from "./rules.module.css";

export default function Rules () {
    return (
        <div className = {styles.rules}>
            <div className = {styles.title}>
                <h3>Rules of use</h3>
            </div>
            <div className = {styles.rulesInfo}>
                
                <p>By registering on the Auto.am website or application, you accept these <strong>Terms of Use.</strong></p> <br></br>
                <p >- - The Carshop website is not responsible for the content of the announcements on the sale of cars on the website (price, accuracy of information about the car / vehicle, etc.).</p> <br></br>
                <p >- It is allowed to post up to 10 ads on the Auto.am website per account, including:</p>
                <p >- - In order to place more than 10 cars on one account, it is necessary to sign an annual contract, which will enable you to get <a className =  {styles.link}  href = "https://carshop.am" target = "_blank">dealer status</a>. You can <a className = {styles.link} href ="https://carshop.am" target = "_blank">apply us </a>to learn more about the terms of the contract and the opportunities provided to dealers.</p><br></br>
                <p >- The same person <b>is not allowed</b> to install several cars with different accounts. Sign up once and use the same account to post your other ads.</p> <br></br>
                <p > - <b>It is not allowed to repeat the same statement</b> by placing it in different makes and models. Place the ad for one vehicle once, exactly in its make and model.</p> <br></br>
                <p > - <b>It is not allowed</b> to post announcements and information not related to the car (spare parts, real estate, etc.) in the announcement.</p> <br></br>
                <p >- <b>It is not allowed</b> to post announcements for the purchase of cars and other vehicles</p> <br></br>
                <p >- <b>It is not allowed</b> to place additional text information, signs or labels related to the announcement in the pictures of the announcement. </p> <br></br>
                <p >- <b>It is not allowed</b> to indicate that the location of the vehicle is in Armenia, if it is located abroad or on the road. </p> <br></br>
                <p >- <b>It is not allowed</b> to indicate that the means of transport is customs cleared, if it is located abroad and has not yet been cleared in Armenia.</p> <br></br>
                <p>- <b>It is not allowed</b>to mention the names of companies or organizations in the Personal Data section, in the first and last name fields. Only the Dealer account provides such an opportunity.</p> <br></br>
                <p>- <b>It is not allowed</b> to indicate the value of the means of transport at illogically lower than market prices. We consider such price manipulations an unscrupulous tool to gain attention in search results.</p> <br></br>
                <p > Violation of these terms will result in account suspension <b>WITHOUT NOTICE.</b></p> <br></br>
                <p > * blocking is a technical tool that does not allow the user who has committed a violation and is blocked to use the website's services with the phone number and e-mail address specified during registration. at the address. The posted announcement is saved in the database, but not published, until the end of the posting period. Account blocking can be removed if the user removes the violation and confirms by letter that he will not violate the rules in the future. In case of repeated violations, we reserve the right to block the email. address and phone number without the possibility of recovery.</p> <br></br>
                <p ><b>1. Carshop</b> is a database of motor vehicles for sale. It helps its users to buy and sell cars and other vehicles. Through the site, visitors submit their offers for cars for sale. Carshop does not sell cars directly and is never a party to transactions between sellers or buyers. Therefore, Carshop: a) does not guarantee any transaction between a buyer and seller, b) does not execute or transfer payments on behalf of buyers or sellers, c) does not park, store or transport any vehicles and d) is not responsible for buyers and sellers for possible disagreements or disputes between.</p> <br></br>
                <p ><b>2. Site Content. </b>The information posted on the Auto.am website is the property of the website administration, dealers and other organizations registered on the website, as well as individuals registered on the website. You may copy some of the information on the site for your own personal, non-commercial use, but no part of the site's content may be reproduced, modified, transmitted, distributed, displayed or transmitted for commercial or other purposes without Carshop's written consent. permission. Requests for commercial or other use of the site's content can be made through the Contact page. Carshop is not responsible for the consequences of possible defects on the website. You should not assume that the website or its content is free of any errors. Carshop reserves the right to make further changes to the website; services may be changed, supplemented or discontinued.</p><br></br>
                <p ><b>3. Payments.</b> Posting ads on Carshop is free. Payments are intended only for additional services offered in the sales department. We may at any time, at our sole discretion, completely or partially terminate or change the type and quantity of paid services offered on the Auto.am website by notifying visitors in advance of the nature of the changes.</p> <br></br>
                <p >Payment for services does not imply special treatment of the statement. If the announcement violates the Terms of Use of the site, is placed in an inappropriate section or contains inappropriate information, it will be removed from the site. In this case, it will not be reinstated, the service will not be extended to another statement, and no refund will be issued.</p> <br></br>
                <p >In case of possible technical problems related to the operation of the website, due to which the activation of one of the paid services failed, the Auto.am website guarantees the full provision of the service to the customer in the presence of proof of payment (payment receipts, electronic yard statement / receipts). The amount paid for the services is non-refundable.</p> <br></br>
            
                <p > <b>4. Messages.</b> </p> <br></br>

                <p > Now you can send and receive messages from users registered on Carshop.</p> <br></br>
                <p >To use the messaging feature, you need to register and log in to the site.</p> <br></br>
                <p ><b>How to send and read messages?</b></p>  <br></br>
                <p >At the bottom of the ad page, click the Write to <b>Seller</b> button and write a message in the field that opens.</p> <br></br>
                <p >A message will be sent to the user selling the vehicle, which he can read on his page in the <b>Messages</b> section. In addition, an email will be sent to the user's email address specified during registration.
If you reply, you will also receive your e-mail address. you will receive an email that you have a new message. To read or reply to the email, click the <b>Read Message</b> button. By clicking on it, you can read the reply in the messages section, as well as see new emails from other buyers.</p> <br></br>
                <p > In addition to the letter, you can find out about the availability of new messages from the red numbers in the upper right corner of the site.</p> <br></br>
                <p > <strong>How do I remove a message?</strong></p> <br></br>
                <p >If you want to remove messages from your page, you need to enter the Messages section, select the user, click the menu button in the upper right corner, on the page that opens, under the user's name, click Remove messages and confirm. After confirmation of this action, the messages will be removed from your page, but will be saved for the other user.</p> <br></br>
                <p >If that user contacts you later, you will see their messages again.</p> <br></br>
                 <p ><b>How to block unwanted users?</b> <br></br>
                   If you don't want to receive messages from a user, you can block them.</p> <br></br>
                <p >Blocked users will appear in the messages section in slightly faded colors and marked with the word <b>Blocked </b>in red.</p> <br></br>
                 <p>To unblock blocked users, you need to enter the <b>Messages</b> section, select the user, click the menu button in the upper right corner, click the <b>Blocked</b> button under the user's name on the page that opens and remove the block.</p> <br></br>
                 <p ><b>5. Carshop on social networks.</b></p> <br></br>
                 <p >The Carshop website has the following official pages on social media:</p> <br></br>
                 <p >Facebook` <a className =  {styles.link} href = "https://www.facebook.com" target ="_blank">https://www.facebook.com</a><br></br>
                 Instagram` <a className =  {styles.link}href = "https://www.instagram.com" target ="_blank"> https://www.instagram.com</a><br></br>
                 Ok.ru ` <a className =  {styles.
                
                
                
                } href = "https://ok.ru" target ="_blank">https://ok.ru</a><br></br>
                 Twitter` <a className =  {styles.link} href = "https://twitter.com" target ="_blank"> https://twitter.com</a><br></br>
                 Youtube` <a className =  {styles.link} href = "https://www.youtube.com" target ="_blank">https://www.youtube.com</a></p> <br></br>
                 <p >On social pages, we share news related to our site, global auto news, and also keep in touch with our users.</p> <br></br>
                 <p >Only the mentioned pages are our official pages. Any other pages that use our Carshop domain name or logo have no legal or content relationship with our website.</p> <br></br>
                 <p ><b>6. Carshop's rights.</b> Due to the nature of the site and the volume of messages and announcements, Auto-am cannot monitor and review all of the announcements you post. Auto-am reserves the right, in its sole discretion, at any time and for any reason to review, refuse to publish, move, remove or edit any postings you post. By using this website, you agree that Auto.am a) shall not be liable for any claims, actions or judgments related to or arising out of the Materials, and b) may at any time and for any reason consider, refuse to publish, transfer , remove or edit your postings without liability and without obligation to compensation.</p> <br></br>
                 <p ><b>7. Prohibited Activities.</b> Below is a list of actions that are prohibited to be carried out through the Website: (a) post material that is clearly offensive to the online public, particularly material that promotes racism, extremism, hatred or calls for physical harm to any group or individual; (b) engage in activities or post Material that may are harmful to minors, (c) engage in activities or post Materials that may discriminate against or encourage discrimination against any person, (d) engage in activities or post Materials, or provide information that is fraudulent, false or misleading or encourages (e) post Materials that are pornographic or sexual in nature, (f) post Materials that provide educational information about illegal activities, such as illegal weapons manufacture and trade, violate anyone's privacy, or provide or create computer viruses, (g) engage in activities or post Materials that harvest other Users' passwords or identity verification information for illegal purposes, (h) use any means or program that is normal to the Site. to obstruct or attempt to obstruct the operation, (i) any action aimed at damaging or obtaining the source software code of the Auto.am website.</p> <br></br>
                 <p ><b>8. Termination of Service.</b> You understand and agree that Auto.am may, in its sole discretion and without prior notice, terminate or suspend your access to the Site, and Auto.am may use any other means and remove any Materials if Auto.am- believes that your use of the Site or Materials provided by you (a) violates (i) these Terms of Use, (ii) the rights of Auto.am, Dealers and users, or (iii) any law or regulation, or (b) are based on fraud. Auto.am is not obligated to provide any compensation if your status as a Registered User is terminated because, in Auto.am's sole discretion, you have violated these Terms of Use.</p> <br></br>
                 <p ><b>9. Additional.</b> Thes
                 e Terms of Use may be changed at any time and you will be notified of such changes through updated versions of the Terms of Use posted on this page of the Site. Your continued use of the Site following the posting of modified Terms of Use constitutes your acceptance of those modifications. Auto.am may modify, suspend or limit the operation of any part of the website without prior notice. This website contains links to other websites that are not established or controlled by Auto.am. Auto.am does not endorse, sponsor or guarantee the reliability of the information posted on those websites and is not responsible for the comments, services, messages on those websites.</p> <br></br>
                 <p ><b>10. Registration of personal data.</b> The user's personal data: e-mail address, phone numbers are used only for using the Auto.am website: registration, phone number verification and, if necessary, for contacting the user by Auto.am.</p> <br></br>
                 <p >The Carshop website does not sell personal data of users, does not provide it to a third party and does not publish it for commercial or any other purpose, except for the cases defined by RA legislation.</p> <br></br>
                 <p >Except for the cases specified in the Order, we do not provide any of your Personal Data to third parties without your specific consent.</p> <br></br>
                 <p >Carshop does not have access to your payment cards or other banking data and therefore Auto.am cannot in any way register, collect such data and cannot be held responsible in any way for any damages you suffer as a result of any use of such data (including: without limitation, cases where third parties gain access to such data in any way and take any action).</p> <br></br>
                  <p ><b>Edit personal information</b></p> <br></br>
                  <p >In the Personal data section, you can edit personal data: phone numbers, first and last name, as well as set or change the profile picture. If you change your primary phone number, you will need to confirm it again. To complete the changes in this section, click the Save Changes button.</p> <br></br>
                  <p ><b>Change password</b></p> <br></br>
                  <p >Click the Password button in the left menu, note the old password and write the new password in the fields below. If you don't remember the old one, to get a new password, you need to click on My Page, then Exit, and then click Login and Forgot password buttons. Following the instructions, you will receive a new password.</p>
                  <p ><b>Get a new password</b></p> <br></br>
                  <p >If you have forgotten your password, to get a new one, you need to click My page, Login and I forgot my password buttons. Enter your e-mail address. address with which you registered on Auto.am, click the Get new password button and follow the instructions.</p>
                  <p ><b>Social accounts</b></p> <br></br>
                  <p >Here you have the opportunity to link your account with your Facebook or Google accounts, which will allow you to access the site faster and easier in the future and make your page more reliable.</p>
                  <p ><b>Change email address</b></p> <br></br>
                  <p >You cannot change the email address because your ads are linked to that email. with the email address, which is also the username to access the website. If you still want to change it, you need to delete your account and register again with a new email. at the postal address.</p>
                  <p ><b>11. Delete account</b></p> <br></br>
                  <p >If you want to delete your account on the Auto.am website, you need to click the Delete Account button located in the Personal Data section. To do this, you need to log in to the website, then click the My Page button in the upper right corner, then the Personal Information page. Click the delete button, then specify the reason, confirm that you want to delete My Page, and click Yes, delete the red button.
                   After deleting your account, all your personal information and statements will be deleted from the Site.
                   If you do not remember your login data and cannot access the website, or in any other case, if you want the website to stop processing your personal data, you need to contact the website administration using the contact page, or send an email to support@auto.am To the electronic address, after which the representative of the Website will contact you in order to confirm your identity. In the case of identity verification, the Website will stop processing your personal data and delete the personal data from the website on the day of verification or during the following business day.</p>
                  <p ><b>Disable Facebook account from Carshop website</b></p> <br></br>
                  <p >When registering users with a Facebook account on the Auto.am website, the Auto.am website uses your Facebook name and email address.</p> <br></br>
                  <p >The user's personal data: e-mail address, phone numbers are used only for using the Auto.am website: registration, phone number verification and, if necessary, for contacting the user by Carshop.</p> <br></br>
                  <p >If you want to disconnect your account from the Facebook account, you need to open the Facebook website, go to your personal page, then click the dot yesterday in the menu next to Edit Personal Page, click Profile and Tagging Settings, click Apps and websites in the left menu that opens. On the opened page, we will see the applications and websites that are attached to your Facebook account. In that list, select Auto.am and click the Removed button on the right, then click the Remove button again on the page that opens.</p> <br></br>
                  <p >If you have lost your Carshop login data, you can contact us using the following link.<a className =  {styles.link} href ="https://carshop.am" target ="_blank">https://carshop.am</a> </p> <br></br>
                  <p >At any time in the future, you can log back into the site with your Facebook account.</p> <br></br>
                  <p ><b>12. Software.</b> All website and application software is the property of AEM Automotive LLC and is protected by copyright and intellectual property laws. Any use of the Website and Application Software is prohibited by law.</p> <br></br>
                 
            </div>
        </div>
    )
}