import styles from "./rules.module.css";

export default function Rules () {
    return (
        <div className = {styles.rules}>
            <div className = {styles.title}>
                <h3>Rules of use</h3>
            </div>
            <div className = {styles.rulesInfo}>
                <p className = {styles.rulesText}>

                </p>
                <p className = {styles.rulesText}>By registering on the Auto.am website or application, you accept these <strong>Terms of Use.</strong></p>
                <p className = {styles.rulesText}>- - The Carshop website is not responsible for the content of the announcements on the sale of cars on the website (price, accuracy of information about the car / vehicle, etc.).</p>
                <p className = {styles.rulesText}>- It is allowed to post up to 10 ads on the Auto.am website per account, including:</p>
                <p className = {styles.rulesText}>- - In order to place more than 10 cars on one account, it is necessary to sign an annual contract, which will enable you to get dealer status. You can <a href ="" target></a>contact us to learn more about the terms of the contract and the opportunities provided to dealers.</p>
                <p className = {styles.rulesText}>- Չի թույլատրվում նույն անձին տեղադրել մի քանի ավտոմեքենա տարբեր հաշիվներով (account): Գրանցվեք մեկ անգամ և օգտագործեք նույն հաշիվը  ձեր մյուս հայտարարությունները տեղադրելու համար:</p>
                <p className = {styles.rulesText}>- Չի թույլատրվում կրկնել նույն հայտարարությունը՝ տեղադրելով այն տարբեր մակնիշների եւ մոդելների մեջ։ Մեկ տրանսպորտային միջոցի հայտարարությունը տեղադրեք մեկ անգամ՝ հենց իր մակնիշի եւ մոդելի մեջ։</p>
                <p className = {styles.rulesText}> - Չի թույլատրվում հայտարարության մեջ տեղադրել ավտոմեքենային չվերաբերող հայտարարություններ և տեղեկատվություն (պահեստամասեր, անշարժ գույք և այլն):</p>
                <p className = {styles.rulesText}> - Չի թույլատրվում հայտարարության մեջ տեղադրել ավտոմեքենաներ և այլ տրանսպորտային միջոցների գնման հայտարարություններ</p>
                <p className = {styles.rulesText}>- Չի թույլատրվում հայտարարության նկարների մեջ տեղադրել հայտարարությանը վերաբերող լրացուցիչ տեքստային ինֆորմացիա, նշաններ կամ պիտակներ։</p>
                <p className = {styles.rulesText}>- Չի թույլատրվում նշել, որ տրանսպորտային միջոցի գտնվելու վայրը Հայաստանում է, եթե այն գտնվում արտերկրում կամ ճանապարհին է: </p>
                <p className = {styles.rulesText}>- Չի թույլատրվում նշել, որ տրանսպորտային միջոցը մաքսազերծված է, եթե այն գտնվում է արտերկրում եւ դեռեւս չի մաքսազերծվել Հայաստանում: </p>
                <p className = {styles.rulesText}>- Չի թույլատրվում Անձնական տվյալներ բաժնում, անուն ազգանուն դաշտերում նշել ընկերությունների կամ կազմակերպությունների անվանումներ: Նման հնարավորություն տալիս է միայն Դիլերական հաշիվը։</p>
                <p className = {styles.rulesText}>- Չի թույլատրվում տրասնպորտային միջոցի արժեքը նշել շուկայականից անտրամաբանական ցածր գներով։ Նման գնային մանիպուլյացիաները մենք համարում ենք ոչ բարեխիղճ գործիք՝ որոնման արդյուքներում ուշադրություն գրավելու համար։</p>
                <p className = {styles.rulesText}>- Խորհուրդ ենք տալիս ավտոմեքենայի գինը նշել ՀՀ դրամով` “Արժութային կարգավորման և արժութային վերահսկողության մասին” օրենքի համաձայն: Կայքի այցելուները միաժամանակ կարող են տեսնել գինը նաև ԱՄՆ դոլարով և եվրոյով`  ավտոմատ փոխարկման համակարգի օգնությամբ:</p>
                <p className = {styles.rulesText}>Այս պայմանները խախտելու դեպքում հաշիվը կարգելափակվի` ԱՌԱՆՑ ՆԱԽԱԶԳՈՒՇԱՑՄԱՆ:</p>
                <p className = {styles.rulesText}>* արգելափակումը տեխնիկական գործիք է, որը թույլ չի տալիս խախտում կատարած եւ արգելափակված օգտատերին այլեւս օգտվել կայքի ծառայություններից գրանցման ընթացքում նշված հեռախոսահամարով եւ էլ. հասցեով։ Տեղադրված հայտարարությունը պահպանվում է բազայում, բայց չի հրապարկվում, մինչեւ տեղադրման ժամկետի ավարտը։ Հաշվի արգելափակումը կարող է հանվել, եթե օգտատերը վերացնի խախտումը եւ նամակով հաստատի, որ հետագայում չի խախտի կանոնները: Խախտումները կրկնելու դեպքում մենք իրավունք ենք վերապահում արգելափակել էլ. հասցեն եւ հեռախոսահամարը՝ առանց վերականգնելու հնարավորության:</p>
                <p className = {styles.rulesText}>1. Auto-am-ը վաճառվող ավտոտրանսպորտային միջոցների բազա է. Այն օգնում է իր օգտատերերին գնել և վաճառել ավտոմեքենաներ և այլ տրանսպորտային միջոցներ։ Կայքի միջոցով այցելուները ներկայացնում են իրենց առաջարկները վաճառվող ավտոմեքենաների մասին: Auto.am-ը ավտոմեքենաների ուղղակի վաճառք չի իրակայացնում և վաճառողների կամ գնորդների միջև գործարքների կողմ երբևէ չի հանդիսանում: Հետևաբար, Auto.am-ը` ա) չի երաշխավորում որևէ գործարք գնորդի և վաճառողի միջև, բ) չի իրականացնում կամ փոխանցում վճարումներ գնորդների կամ վաճառողների անունից, գ) չի կայանում, պահեստավորում կամ փոխադրում որևէ տրանսպորտային միջոցներ և դ) պատասխանատու չէ գնորդների և վաճառողների միջև առաջացած հնարավոր տարաձայնությունների կամ վեճերի համար:</p>
                <p className = {styles.rulesText}>2. Կայքի բովանդակությունը: Auto.am կայքում տեղադրված տեղեկատվությունը հանդիսանում է կայքի ադմինիստրացիայի, կայքում գրանցված դիլերների և այլ կազմակերպությունների, ինչպես նաև կայքում գրանցված անհատների սեփականությունը: Դուք կարող եք կրկնօրինակել կայքում զետեղված տեղեկատվության ինչ-որ մաս ձեր անձնական, ոչ կոմերցիոն գործունեության համար, սակայն կայքի բովանդակության ոչ մի մաս չի կարող վերարտադրվել, ձևափոխվել, փոխանցվել, տարածվել, ցուցադրվել կամ ուղարկվել կոմերցիոն կամ այլ նպատակներով` առանց Auto-am-ի գրավոր թույլտվության: Կայքի բովանդակությունը կոմերցիոն կամ այլ նպատակներով օգտագործելու վերաբերյալ դիմումներ կարող են ուղարկվել Կապի էջի միջոցով: Auto-am-ը պատասխանատվություն չի կրում վեբ-կայքում առկա հնարավոր թերությունների հետևանքների համար: Դուք չպետք է համարեք, որ վեբ-կայքը կամ դրա բովանդակությունը չի պարունակում որևէ սխալներ: Auto-am-ը իրավունք է վերապահում կատարել հետագա փոփոխություններ վեբ-կայքում. ծառայությունները կարող են փոփոխվել, լրացվել կամ դադարեցվել:</p>
                <p className = {styles.rulesText}>3. Վճարումներ: Auto.am կայքում հայտարարությունների տեղադրումն անվճար է։ Վճարումներ նախատեսված են միայն վաճառքի բաժնում առաջարկվող լրացուցիչ ծառայությունների դիմաց: Մենք կարող ենք ցանկացած ժամանակ մեր հայեցողությամբ ամբողջությամբ կամ մասամբ դադարեցնել կամ փոփոխել Auto.am կայքում առաջարկվող վճարովի ծառայությունների տեսակը և քանակը` նախապես տեղեկացնելով այցելուներին փոփոխությունների բնույթի մասին։</p>
                <p className = {styles.rulesText}>Կայքի աշխատանքի հետ կապված հնարավոր տեխնիկական խնդիրների դեպքում, որոնց պատճառով ձախողվել է վճարովի ծառայություններից մեկի ակտիվացումը, Auto.am կայքը երաշխավորում է ծառայության ամբողջովին մատուցումը հաճախորդին` վճարման ապացույցների առկայության դեպքում (վճարման անդորրագրեր, բակային էլէկտրոնային տեղեկանք / անդորրագրեր): Ծառայությունների դիմաց վճարված գումարը չի վերադարձվում:
                  Վճարովի ծառայությունների ակտիվացումը կարող է ձախողվել ինչպես կայքում ծագած, այնպես էլ Auto.am-ում ներկայացված վճարային համակարգերում առաջացած խնդիրների պատճառով: Տվյալ դեպքերում հաճախորդները պետք է դիմեն նշված վճարային համակարգերի սպասարկման ծառայություններին, կամ իրենց քարտը սպասարկող Բանկին:</p>
            
                <p>4. Հաղորդագրություններ:

                   Այժմ դուք կարող եք ուղարկել և ստանալ հաղորդագրություններ Auto.am կայքում գրանցված օգտատերերից։</p>
                <p>Հաղորդագրությունների հնարավորությունից օգտվելու համար ահնրաժեշտ է գրանցվել և մուտք գործել կայք։</p>
                <p> Ինչպե՞ս ուղարկել և կարդալ հաղորդագրությունները</p> 
                <p>Հայտարարության էջի ներքևի մասում սեղմեք Գրել Վաճառողին կոճակը և բացվող դաշտում գրեք հաղորդագրությունը։</p>
                <p>Հաղորդագրությունը կուղարկվի տվյալ տրանսպորտային միջոցը վաճառող օգտատիրոջը, որը նա կարող է կարդալ իր էջում՝ Հաղորդագրություններ բաժնում։ Բացի այդ, օգտատիրոջը կուղարկվի նամակ՝ գրանցման ընթացքում նշված նրա էլ հասցեին։
                   Պատասխանելու դեպքում Դուք նույնպես ձեր էլ․ հասցեին կստանաք նամակ այն մասին, որ ունեք նոր հաղորդագրություն։ Նամակը կարդալու կամ պատասխանելու համար պետք է սեղմել Կարդալ հաղորդագրությունը կոճակը։ Սեղմելով այն, հաղորդագրություններ բաժնում կարող եք կարդալ պատասխանը, ինչպես նաև տեսնել նոր նամակներ այլ գնորդներից։</p>
                <p> Բացի նամակից, նոր հաղորդագրությունների առկայության մասին կարելի է տեղեկանալ կայքի վերևի աջ անկյունում կարմիր թվերից:</p>
                <p> <strong>Ինչպե՞ս արգելափակել անցանկալի օգտատերերին</strong></p>
                <p>Եթե Դուք չեք ցանկանում հաղորդագրություններ ստանալ որևէ օգտատիրոջից, ապա կարող եք արգելափակել նրան:</p>
                <p>Դրա համար անհրաժեշտ է մտնել Հաղորդագրություններ բաժին, ընտրել օգտատիրոջը, վերևի աջ անկյունում սեղմել մենյուի կոճակը, բացվող էջում օգտատիրոջ անվան տակ սեղմել Արգելափակել և հաստատել:</p>
                <p>Արգելափակված օգտատերերը հաղորդագրությունների բաժնում կերևան քիչ խամրած գույներով և կնշվեն կարմիրով Արգելափակված բառով։</p>
                 <p>Արգելափակված օգտատերերին արգելափակումից հանելու համար անհրաժեշտ է մտնել Հաղորդագրություններ բաժին, ընտրել օգտատիրոջը, վերևի աջ անկյունում սեղմել մենյուի կոճակը, բացվող էջում օգտատիրոջ անվան տակ սեղմել Արգելափկված կոճակը և հանել արգելափակումը:</p>
                 <p>5. Auto.am-ը սոցիալական ցանցերում:</p>
                 <p>The Carshop website has the following official pages on social media:</p>
                 <p>Facebook` https://www.facebook.com/auto.am/
                 Instagram` https://www.instagram.com/auto.am/
                 Ok.ru ` https://ok.ru/auto.am
                 Twitter` https://twitter.com/autodotam/
                 Youtube` https://www.youtube.com/AutoamCarNews</p>
                 <p>On social pages, we share news related to our site, global auto news, and also keep in touch with our users.</p>
                 <p>Only the mentioned pages are our official pages. Any other pages that use our Carshop domain name or logo have no legal or content relationship with our website.</p>
                 <p>6. Auto.am's rights. Due to the nature of the site and the volume of messages and announcements, Auto-am cannot monitor and review all of the announcements you post. Auto-am reserves the right, in its sole discretion, at any time and for any reason to review, refuse to publish, move, remove or edit any postings you post. By using this website, you agree that Auto.am a) shall not be liable for any claims, actions or judgments related to or arising out of the Materials, and b) may at any time and for any reason consider, refuse to publish, transfer , remove or edit your postings without liability and without obligation to compensation.</p>
                 <p>7. Prohibited Activities. Below is a list of actions that are prohibited to be carried out through the Website: (a) post material that is clearly offensive to the online public, particularly material that promotes racism, extremism, hatred or calls for physical harm to any group or individual; (b) engage in activities or post Material that may are harmful to minors, (c) engage in activities or post Materials that may discriminate against or encourage discrimination against any person, (d) engage in activities or post Materials, or provide information that is fraudulent, false or misleading or encourages (e) post Materials that are pornographic or sexual in nature, (f) post Materials that provide educational information about illegal activities, such as illegal weapons manufacture and trade, violate anyone's privacy, or provide or create computer viruses, (g) engage in activities or post Materials that harvest other Users' passwords or identity verification information for illegal purposes, (h) use any means or program that is normal to the Site. to obstruct or attempt to obstruct the operation, (i) any action aimed at damaging or obtaining the source software code of the Auto.am website.</p>
                 <p>8. Termination of Service. You understand and agree that Auto.am may, in its sole discretion and without prior notice, terminate or suspend your access to the Site, and Auto.am may use any other means and remove any Materials if Auto.am- believes that your use of the Site or Materials provided by you (a) violates (i) these Terms of Use, (ii) the rights of Auto.am, Dealers and users, or (iii) any law or regulation, or (b) are based on fraud. Auto.am is not obligated to provide any compensation if your status as a Registered User is terminated because, in Auto.am's sole discretion, you have violated these Terms of Use.</p>
                 <p>9. Additional. These Terms of Use may be changed at any time and you will be notified of such changes through updated versions of the Terms of Use posted on this page of the Site. Your continued use of the Site following the posting of modified Terms of Use constitutes your acceptance of those modifications. Auto.am may modify, suspend or limit the operation of any part of the website without prior notice. This website contains links to other websites that are not established or controlled by Auto.am. Auto.am does not endorse, sponsor or guarantee the reliability of the information posted on those websites and is not responsible for the comments, services, messages on those websites.</p>
                 <p>10. Registration of personal data. The user's personal data: e-mail address, phone numbers are used only for using the Auto.am website: registration, phone number verification and, if necessary, for contacting the user by Auto.am.</p>
                 <p>The Auto.am website does not sell personal data of users, does not provide it to a third party and does not publish it for commercial or any other purpose, except for the cases defined by RA legislation.</p>
                 <p>Except for the cases specified in the Order, we do not provide any of your Personal Data to third parties without your specific consent.</p>
                 <p>Carshop does not have access to your payment cards or other banking data and therefore Auto.am cannot in any way register, collect such data and cannot be held responsible in any way for any damages you suffer as a result of any use of such data (including: without limitation, cases where third parties gain access to such data in any way and take any action).</p>

            
            </div>
        </div>
    )
}